### PR TITLE
Support Option of sum types

### PR DESCRIPTION
**Pull request by erikvanoosten**
The type `Option[A]` for any sum type `A` should be supported. Right now this fails with `org.apache.avro.AvroRuntimeException: Nested union` (see https://github.com/fd4s/vulcan/issues/442 problem 1).

This is because `Codec[Option[_]]` is build from a `UnionCodec` which references a nested `UnionCodec`. We solve the problem by creating a special `Codec` for `Option`s.

### CODE REVIEW

**Comment by erikvanoosten** [comment]
@bplommer this is ready for review now

**Comment by bplommer** [comment]
Hi, thanks for this and sorry for the long silence! This looks good, but I'd like to try and solve it in a more generic way by making the union codec flatten nested unions in the schema. So I'm going to leave this open for now.

**Comment by erikvanoosten** [comment]
Adapting the union codec was also my first attempt. I had a hard time aligning all the types. When I switched to this approach all went pretty smooth.

**Comment by bplommer** [comment]
I came up with something but it’s not quite as robust because of the way the union codec uses heuristics in decoding, so I’m going to merge this as a special case. Thanks!

**Review by bplommer — APPROVED** [review]

**Pull request merged**
