### PR TITLE
add vulcan-fuuid module

### PR DESCRIPTION
**Pull request by JackTreble**
add fuuid support

tests might be too much

### CODE REVIEW

**Comment by bplommer** [comment]
I wonder if this should be a separate repo, since fuuid is pre-1.0?

**Comment by JackTreble** [comment]
> I wonder if this should be a separate repo, since fuuid is pre-1.0?

@bplommer 
whatever you think is best, would that be within fd4s?

have you encountered the same issue with the CI before?

**Comment by bplommer** [comment]
>
> @bplommer 
> 
> whatever you think is best, would that be within fd4s?

That's what I'm thinking. @vlovgr is there anything particular I should know before setting up a new repo?

> have you encountered the same issue with the CI before?

I think it's trying to check binary compatibility but can't because it's a new module. Probably need to temporarily set mimaPreviousArtifacts to None for that module.

**Comment by vlovgr** [comment]
> @vlovgr is there anything particular I should know before setting up a new repo?

I'll have to setup the secrets for GitHub Actions, but can't think of anything else at the moment.

**Comment by JackTreble** [comment]
Started implementing here https://github.com/fd4s/vulcan-fuuid/pull/1

**Pull request closed without merging**
