### PR TITLE
scala 3 support for core + refined

### PR DESCRIPTION
**Pull request by bplommer**
`Codec.deriveEnum` and `Codec.deriveFixed` had to be made specific to scala 2, because they depend on TypeTag - I'll look into bringing them back using `typename` as mentioned in #238, though I do wonder whether we shouldn't move autoderivation out into a separate module anyway.

Had to disable scoverage because it doesn't support dotty, but might be able to re-enable it for scala 2

### CODE REVIEW

**Comment by vlovgr** [comment]
@bplommer my thinking is we could move all the `Codec.derive*` functions to the generic module.

**Comment by bplommer** [comment]
> @bplommer my thinking is we could move all the `Codec.derive*` functions to the generic module.

Sounds good. Let's initially copy/alias them there and deprecate them in `core`?

**Comment by vlovgr** [comment]
> > @bplommer my thinking is we could move all the `Codec.derive*` functions to the generic module.
>
> Sounds good. Let's initially copy/alias them there and deprecate them in `core`?

Yes, let's have at least one round of deprecation before removing them in the next major release. 👍

**Comment by bplommer** [comment]
The only thing blocking this is sbt-scoverage, which shows no signs of planning to support scala 3. Ideally we'd continue to report coverage for scala 2, but that's going to require quite a lot of refactoring of the build. What do you think about dropping it for now @vlovgr ?

**Comment by bplommer** [comment]
I'm tempted to deprecate `Codec.enum` in favour of `Codec.enumeration` to avoid the issue with `enum` being a keyword in scala 3 - thoughts?

**Comment by vlovgr** [comment]
> What do you think about dropping it for now @vlovgr ?
👍 

> I'm tempted to deprecate `Codec.enum` in favour of `Codec.enumeration` to avoid the issue with `enum` being a keyword in scala 3 - thoughts?

Is `enum` a soft or hard keyword? If it's a hard keyword, then we should definitely do this.

**Comment by bplommer** [comment]
> Is `enum` a soft or hard keyword? If it's a hard keyword, then we should definitely do this.

Hard. I'll make that change.

**Comment by bplommer** [comment]
@vlovgr shall we merge this and follow up with another PR to move `deriveEnum` to `vulcan-generic`?

**Comment by vlovgr** [comment]
> @vlovgr shall we merge this and follow up with another PR to move `deriveEnum` to `vulcan-generic`?

Sounds good to me.

**Pull request merged**
