### PR TITLE
Record field default annotation

### LINKED ISSUE #525: Default value annotation for a record type
To maintain backward compatibility, I would like to be able to do this:

```scala
  case class Foo(
    @AvroFieldDefault(1) a: Int,
    @AvroFieldDefault("foo") b: String,
  )

  object Foo {
    implicit val codec: Codec[Foo] = Codec.derive
  }
```

### PR DESCRIPTION
**Pull request by soujiro32167**
Closes #525

### CODE REVIEW

**Comment by regis-leray** [comment]
Ah good one @soujiro32167 :)

**Comment by soujiro32167** [comment]
Its not typesafe...but it works =]

**Comment by mberndt123** [comment]
I'd like to propose a type-safe alternative in #566.

**Comment by soujiro32167** [comment]
Closing in favor of https://github.com/fd4s/vulcan/pull/566

**Pull request closed without merging**
